FROM docker.io/tomcat:9.0.68-jdk17 as stage1

ARG WAR_FILE=target/*.war

RUN mkdir -p /app/samplewarapp

COPY ${WAR_FILE} /app/samplewarapp/samplewarapp.war

WORKDIR /app/samplewarapp
RUN jar -xf samplewarapp.war && rm samplewarapp.war


FROM docker.io/tomcat:9.0.68-jdk17
ARG PROJECT_DIR=app
COPY --from=stage1 ${PROJECT_DIR} /usr/local/tomcat/webapps/



RUN addgroup  springboot && adduser tomcat
RUN usermod -G springboot tomcat
RUN chown -R tomcat /usr/local/tomcat
USER tomcat

EXPOSE 8080
