FROM docker.io/tomcat:9.0.68-jdk17


RUN mkdir /usr/local/tomcat/webapps/samplewarapp

COPY /target/sb-war-docker-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/samplewarapp/app.war

RUN cd /usr/local/tomcat/webapps/samplewarapp && jar xf app.war && rm app.war && cd /usr/local/tomcat

RUN addgroup  springboot && adduser tomcat
RUN usermod -G springboot tomcat
RUN chown -R tomcat /usr/local/tomcat

USER tomcat
EXPOSE 8080