version: '3'

services:
  sb-war-app:
    image: 'docker.io/tomcat:9.0.68-jdk17'
    ports:
      - 8080:8080
    volumes:
      - ../target/sb-war-docker-0.0.1-SNAPSHOT.war:/usr/local/tomcat/webapps/samplewarapp.war